const products = [
 {id:1,name:'Bare Vanilla Fragrance Mist',brand:"Victoria's Secret",price:169.9,volume:'250 ml',family:'Gourmand',vibe:'Doce',intensity:'Moderada',notes:['baunilha','cashmere'],rating:4.9,badge:'Queridinho',isNew:false,source:'Produto real de referência',image:'',occasion:'Dia a dia'},
 {id:2,name:'Pure Seduction Fragrance Mist',brand:"Victoria's Secret",price:169.9,volume:'250 ml',family:'Frutado',vibe:'Sensual',intensity:'Marcante',notes:['ameixa','frésia'],rating:4.9,badge:'Mais vendido',isNew:false,source:'Produto real de referência',image:'',occasion:'Encontro'},
 {id:3,name:'Love Spell Fragrance Mist',brand:"Victoria's Secret",price:169.9,volume:'250 ml',family:'Floral',vibe:'Romântica',intensity:'Marcante',notes:['maçã vermelha','flor de cerejeira','pêssego'],rating:4.9,badge:'Clássico',isNew:false,source:'Produto real de referência',image:'',occasion:'Dia a dia'},
 {id:4,name:'Velvet Petals Fragrance Mist',brand:"Victoria's Secret",price:179.9,volume:'250 ml',family:'Floral',vibe:'Elegante',intensity:'Moderada',notes:['florais','amêndoa'],rating:4.8,badge:'Elegante',isNew:false,source:'Produto real de referência',image:'',occasion:'Noite'},
 {id:5,name:'Aqua Kiss Fragrance Mist',brand:"Victoria's Secret",price:159.9,volume:'250 ml',family:'Fresco',vibe:'Fresca',intensity:'Leve',notes:['notas aquáticas','flores'],rating:4.8,badge:'Fresh',isNew:true,source:'Produto real de referência',image:'',occasion:'Depois do banho'},
 {id:6,name:'Amber Romance Fragrance Mist',brand:"Victoria's Secret",price:169.9,volume:'250 ml',family:'Gourmand',vibe:'Sensual',intensity:'Marcante',notes:['âmbar','baunilha'],rating:4.8,badge:'Marcante',isNew:false,source:'Produto real de referência',image:'',occasion:'Noite'},
 {id:7,name:'Coconut Passion Fragrance Mist',brand:"Victoria's Secret",price:169.9,volume:'250 ml',family:'Gourmand',vibe:'Doce',intensity:'Moderada',notes:['coco','baunilha'],rating:4.8,badge:'Cremoso',isNew:true,source:'Produto real de referência',image:'',occasion:'Dia a dia'},
 {id:8,name:'Love Spell Brulee Fragrance Mist',brand:"Victoria's Secret",price:149.9,volume:'250 ml',family:'Gourmand',vibe:'Doce',intensity:'Marcante',notes:['mel','pêssego','sândalo açucarado'],rating:4.8,badge:'Novidade',isNew:true,source:'Produto real de referência',image:'',occasion:'Encontro'}
];
let state={filters:{},cart:[],favorites:[],compare:[],quizAnswers:[]};
const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function productVisual(p){return p.image?`<img src="${p.image}" alt="${p.name}">`:`<div class="product-placeholder">${p.name.split(' ')[0]}</div>`}
function card(p){return `<article class="product-card"><div class="product-image">${productVisual(p)}<span class="badge">${p.badge}</span><button class="heart" onclick="toggleFav(${p.id})">${state.favorites.includes(p.id)?'♥':'♡'}</button></div><div class="product-info"><div class="meta">${p.brand} • ${p.volume}</div><h3>${p.name}</h3><div class="meta">${p.family} • ${p.intensity} • ★ ${p.rating}</div><div class="notes">Notas: ${p.notes.join(', ')}</div><div class="price">${money(p.price)} <span class="meta">ou 3x sem juros*</span></div><div class="card-actions"><button onclick="toggleCompare(${p.id})">${state.compare.includes(p.id)?'✓ Comparando':'Comparar'}</button><button class="buy" onclick="addCart(${p.id})">Adicionar</button></div></div></article>`}
function filtered(){let list=[...products];for(const [k,v] of Object.entries(state.filters)){if(v)list=list.filter(p=>p[k]===v)}const s=document.querySelector('#sort').value;if(s==='price-asc')list.sort((a,b)=>a.price-b.price);if(s==='price-desc')list.sort((a,b)=>b.price-a.price);if(s==='rating')list.sort((a,b)=>b.rating-a.rating);return list}
function renderProducts(){document.querySelector('#productGrid').innerHTML=filtered().map(card).join('')||'<p>Nenhum produto encontrado com esses filtros.</p>';document.querySelectorAll('.filters button[data-filter]').forEach(b=>b.classList.toggle('active',state.filters[b.dataset.filter]===b.dataset.value))}
function addCart(id){const existing=state.cart.find(x=>x.id===id);if(existing)existing.qty++;else state.cart.push({id,qty:1});renderCart()}
function renderCart(){document.querySelector('#cartCount').textContent=state.cart.reduce((a,b)=>a+b.qty,0);const el=document.querySelector('#cartItems');if(!state.cart.length){el.innerHTML='<p>Seu carrinho está vazio.</p>'}else el.innerHTML=state.cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="drawer-item"><div class="drawer-thumb"></div><div><strong>${p.name}</strong><small>${i.qty}x • ${money(p.price)}</small></div><button onclick="removeCart(${p.id})">×</button></div>`}).join('');document.querySelector('#cartSubtotal').textContent=money(state.cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0))}
function removeCart(id){state.cart=state.cart.filter(i=>i.id!==id);renderCart()}
function toggleFav(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];document.querySelector('#favCount').textContent=state.favorites.length;renderProducts();renderFavorites()}
function renderFavorites(){const el=document.querySelector('#favoritesItems');el.innerHTML=state.favorites.length?state.favorites.map(id=>{const p=products.find(x=>x.id===id);return `<div class="drawer-item"><div class="drawer-thumb"></div><div><strong>${p.name}</strong><small>${money(p.price)}</small></div><button onclick="toggleFav(${p.id})">×</button></div>`}).join(''):'<p>Você ainda não favoritou produtos.</p>'}
function toggleCompare(id){if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else if(state.compare.length<3)state.compare.push(id);else alert('Você pode comparar até 3 fragrâncias.');renderProducts();document.querySelector('#comparePreview').innerHTML=`<span>${state.compare.length}/3 selecionadas</span><p>${state.compare.map(id=>products.find(p=>p.id===id).name).join(' • ')||'Use o botão “Comparar” nos cards dos produtos.'}</p>`}
function openCompare(){const list=state.compare.map(id=>products.find(p=>p.id===id));const el=document.querySelector('#compareTable');if(!list.length){el.innerHTML='<p>Selecione produtos nos cards para comparar.</p>'}else{const rows=['price','volume','family','intensity','notes','occasion','rating'];const labels={price:'Preço',volume:'Volume',family:'Família',intensity:'Intensidade',notes:'Notas',occasion:'Ocasião',rating:'Avaliação'};el.innerHTML=`<table class="compare-table"><thead><tr><th>Característica</th>${list.map(p=>`<th>${p.name}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td>${labels[r]}</td>${list.map(p=>`<td>${r==='price'?money(p[r]):Array.isArray(p[r])?p[r].join(', '):p[r]}</td>`).join('')}</tr>`).join('')}</tbody></table>`}document.querySelector('#compareModal').classList.add('open')}
const quiz=[{q:'Como você gosta de se sentir usando uma fragrância?',opts:['Romântica','Sensual','Elegante','Doce','Fresca']},{q:'Qual aroma mais chama sua atenção?',opts:['Baunilha','Flores','Frutas','Coco','Aromas frescos']},{q:'Você prefere fragrâncias…',opts:['Leve','Moderada','Marcante']},{q:'Quando você mais pretende usar?',opts:['Dia a dia','Trabalho','Encontro','Festa','Depois do banho','Noite']},{q:'Escolha sua vibe.',opts:['Soft girl','Clean girl','Romantic','Glam','Sexy','Fresh']}];let qi=0;
function renderQuiz(){const q=quiz[qi];document.querySelector('#quizProgress').textContent=`${qi+1} de ${quiz.length}`;document.querySelector('#quizQuestion').textContent=q.q;document.querySelector('#quizOptions').innerHTML=q.opts.map(o=>`<button onclick="answerQuiz('${o.replace(/'/g,"\\'")}')">${o}</button>`).join('')}
function answerQuiz(a){state.quizAnswers.push(a);qi++;if(qi<quiz.length)renderQuiz();else quizResult()}
function quizResult(){let score=products.map(p=>({p,s:0}));const a=state.quizAnswers;score.forEach(x=>{if(a.includes(x.p.vibe))x.s+=3;if(a.includes(x.p.intensity))x.s+=2;if(a.includes(x.p.occasion))x.s+=2;const txt=a.join(' ').toLowerCase();x.p.notes.forEach(n=>{if(txt.includes(n.split(' ')[0]))x.s+=2});if(txt.includes('frutas')&&x.p.family==='Frutado')x.s+=2;if(txt.includes('flores')&&x.p.family==='Floral')x.s+=2;if(txt.includes('frescos')&&x.p.family==='Fresco')x.s+=2});score.sort((a,b)=>b.s-a.s);const picks=score.slice(0,3).map(x=>x.p);document.querySelector('#quizProgress').textContent='Seu resultado';document.querySelector('#quizQuestion').textContent='Encontramos fragrâncias que combinam com você ♡';document.querySelector('#quizOptions').innerHTML=picks.map(p=>`<div style="border:1px solid var(--line);border-radius:16px;padding:14px"><b>${p.name}</b><p>${p.family} • ${p.notes.join(', ')}</p><button onclick="addCart(${p.id})">Adicionar ao carrinho</button></div>`).join('');document.querySelector('#quizRestart').classList.remove('hidden')}
function resetQuiz(){qi=0;state.quizAnswers=[];document.querySelector('#quizRestart').classList.add('hidden');renderQuiz()}
document.querySelectorAll('.filters button[data-filter]').forEach(b=>b.onclick=()=>{state.filters[b.dataset.filter]=state.filters[b.dataset.filter]===b.dataset.value?'':b.dataset.value;renderProducts()});document.querySelector('#clearFilters').onclick=()=>{state.filters={};renderProducts()};document.querySelector('#sort').onchange=renderProducts;document.querySelector('#cartBtn').onclick=()=>document.querySelector('#cartDrawer').classList.add('open');document.querySelector('#favoritesBtn').onclick=()=>document.querySelector('#favoritesDrawer').classList.add('open');document.querySelector('#searchBtn').onclick=()=>document.querySelector('#searchModal').classList.add('open');document.querySelector('#openCompare').onclick=openCompare;document.querySelector('#menuBtn').onclick=()=>document.querySelector('#nav').classList.toggle('open');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.close).classList.remove('open'));document.querySelector('#searchInput').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelector('#searchResults').innerHTML=products.filter(p=>[p.name,p.family,p.vibe,...p.notes].join(' ').toLowerCase().includes(q)).slice(0,6).map(p=>`<div class="drawer-item"><div class="drawer-thumb"></div><div><strong>${p.name}</strong><small>${p.family} • ${money(p.price)}</small></div><button onclick="addCart(${p.id})">+</button></div>`).join('')};document.querySelector('#quizRestart').onclick=resetQuiz;document.querySelector('#newsletterForm').onsubmit=e=>{e.preventDefault();alert('Cadastro demonstrativo realizado. Integre com sua ferramenta de e-mail marketing na versão de produção.');e.target.reset()};
document.querySelector('#newGrid').innerHTML=products.filter(p=>p.isNew).map(card).join('');renderProducts();renderCart();renderFavorites();renderQuiz();
